---
- hosts: Server-WD
  become: yes
  tasks:

  - name: Copy timezone
    ansible.builtin.copy:
      src: /usr/share/zoneinfo/Europe/Moscow
      dest: /etc/localtime
      owner: root

  - name: Restart chronyd
    ansible.builtin.systemd:
      name: chronyd
      state: restarted
      enabled: yes

  - name: Update the rpm
    ansible.builtin.dnf:
      name:
        - rpm
      state: latest
      update_only: yes

  - name: Add sudo for vagrant
    ansible.builtin.shell:
      cmd: echo "vagrant ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/vagrant

  - name: Add docker repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: yes

  - name: Install packages
    ansible.builtin.dnf:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - nano
      - mc
      - curl
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    tags:
      - docker

  - name: Add remote "vagrant" user to "docker" group
    ansible.builtin.user:
      name: vagrant
      group: "docker"
      append: yes
    tags:
      - docker

  - name: Ensure docker is running and enabled
    ansible.builtin.systemd:
      name: docker
      state: restarted
      enabled: yes

  - name: Create folders /usr/local/bin/docker-compose
    ansible.builtin.shell:
      cmd: mkdir /usr/local/bin/docker-compose

  - name: Install docker-compose
    ansible.builtin.get_url:
      url: https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0777

  - name: Create folders /home/vagrant/project
    ansible.builtin.shell:
      cmd: mkdir /home/vagrant/project

  - name: Copy project
    ansible.builtin.copy:
      src: ./files/
      dest: /home/vagrant/project
      owner: vagrant
      group: docker
      mode: '0774'

  - name: Reset ssh connection 
    ansible.builtin.meta: reset_connection

  - name: Run container
    ansible.builtin.shell:
      cmd: "/usr/local/bin/docker-compose/docker-compose-linux-x86_64 -f docker-compose.yaml up -d"
      chdir: /home/vagrant/project
